local utils = require("utils")

vim.g.mapleader = ","
vim.g.maplocalleader = "\\"
vim.g.base16colorspace = 256

vim.g.python_host_prog = os.getenv("HOME") .. "/.asdf/shims/python2"
vim.g.python3_host_prog = os.getenv("HOME") .. "/.asdf/shims/python3"

vim.api.nvim_command("set whichwrap+=<,>,h,l,[,]")
vim.api.nvim_command("set guioptions-=r")
vim.api.nvim_command("set guioptions-=R")
vim.api.nvim_command("set guioptions-=l")
vim.api.nvim_command("set guioptions-=L")
vim.api.nvim_command("set t_vb=")

utils.opt("o", "backspace", "eol,start,indent")
utils.opt("o", "autoread", true)
utils.opt("o", "cmdheight", 2)
utils.opt("o", "ruler", true)
utils.opt("o", "hlsearch", true)
utils.opt("o", "smartcase", true)
utils.opt("o", "ignorecase", true)
utils.opt("o", "showmatch", true)
utils.opt("o", "matchtime", 2)
utils.opt("o", "errorbells", false)
utils.opt("o", "visualbell", false)
utils.opt("o", "timeoutlen", 500)
utils.opt("o", "splitbelow", true)
utils.opt("o", "splitright", true)
utils.opt("w", "relativenumber", true)
utils.opt("w", "number", true)
utils.opt("o", "encoding", "utf8")
utils.opt("o", "guifont", "Menlo:h12")
utils.opt("o", "fileformats", "unix,dos,mac")
utils.opt("o", "backup", false)
utils.opt("o", "writebackup", false)
utils.opt("o", "swapfile", false)
utils.opt("o", "scrolloff", 7)
utils.opt("o", "undodir", "~/.config/nvim/temp/undodir")
utils.opt("o", "undofile", true)
utils.opt("b", "expandtab", true)
utils.opt("o", "smarttab", true)
utils.opt("b", "shiftwidth", 2)
utils.opt("b", "tabstop", 2)
utils.opt("b", "autoindent", true)
utils.opt("b", "smartindent", true)
utils.opt("o", "wrap", true)
utils.opt("o", "laststatus", 2)
utils.opt("o", "shellpipe", ">")
utils.opt("o", "hidden", true)
utils.opt("o", "termguicolors", true)
utils.opt("o", "modelines", 0)
utils.opt("o", "modeline", false)
utils.opt("w", "foldlevel", 99)
