require("work")
require("settings")
require("plugins")
require("mappings")
require("plugins_config")

require("custom/tmux_test")
require("custom/color_replace")
require("custom/express")
require("custom/navigation")
