#!/usr/bin/env sh

protected_branch="main"
current_branch=$(git rev-parse --abbrev-ref HEAD)

if test "$protected_branch" = "$current_branch"
then
  echo "You should not push directly to main. If you want to bypass this check, run \`git push --no-verify\`"
  exit 1
fi
