require("use")({
  "airblade/vim-gitgutter",
  "ap/vim-css-color",
  "arecarn/vim-fold-cycle",
  "edkolev/tmuxline.vim",
  "fnune/base16-vim",
  "github/copilot.vim",
  "joom/vim-commentary",
  "junegunn/vim-easy-align",
  "justinmk/vim-sneak",
  "lukas-reineke/indent-blankline.nvim",
  "maxbrunsfeld/vim-yankstack",
  "pseewald/vim-anyfold",
  "puremourning/vimspector",
  "ruanyl/vim-gh-line",
  "tpope/vim-abolish",
  "tpope/vim-endwise",
  "tpope/vim-fugitive",
  "tpope/vim-repeat",
  "tpope/vim-surround",
  "vim-airline/vim-airline", -- slow
  "vim-airline/vim-airline-themes",
  { "kyazdani42/nvim-tree.lua", requires = "kyazdani42/nvim-web-devicons" },
  { "neoclide/coc.nvim", branch = "release" },
  { "nvim-telescope/telescope.nvim", tag = '0.1.2', requires = "nvim-lua/plenary.nvim" },
  { "nvim-treesitter/nvim-treesitter", run = ":TSUpdate" },
})
