require("use")({
  "airblade/vim-gitgutter",
  "ap/vim-css-color",
  "arecarn/vim-fold-cycle",
  "edkolev/tmuxline.vim",
  "fnune/base16-vim",
  "joom/vim-commentary",
  "joshddunn/vim-glob",
  "junegunn/fzf",
  "junegunn/fzf.vim",
  "junegunn/vim-easy-align",
  "justinmk/vim-sneak",
  "leafgarland/typescript-vim",
  "maxbrunsfeld/vim-yankstack",
  "maxmellon/vim-jsx-pretty",
  "moll/vim-node",
  "nathanaelkane/vim-indent-guides",
  "noahtheduke/vim-just",
  "pangloss/vim-javascript",
  "pseewald/vim-anyfold",
  "puremourning/vimspector",
  "ruanyl/vim-gh-line",
  "sheerun/vim-polyglot",
  "tpope/vim-abolish",
  "tpope/vim-endwise",
  "tpope/vim-fugitive",
  "tpope/vim-repeat",
  "tpope/vim-surround",
  "vim-airline/vim-airline", -- slow
  "vim-airline/vim-airline-themes",
  "w0rp/ale",
  "github/copilot.vim",
  { "neoclide/coc.nvim", branch = "release" },
  { "kyazdani42/nvim-tree.lua", requires = "kyazdani42/nvim-web-devicons" },
})
