brew "asdf"
brew "fzf"
brew "gh"
brew "neovim"
brew "ripgrep"
brew "tmux"
brew "zsh"

cask "dbeaver-community"
cask "iterm2"
cask "rectangle"

# cask fonts
tap "homebrew/cask-fonts"
cask "font-meslo-lg-nerd-font"
