#!/usr/bin/env ruby

begin
  require 'daemons'
  require 'listen'
rescue LoadError
  require 'bundler/inline'
  puts 'installing...'

  gemfile do
    source 'https://rubygems.org'
    gem 'daemons'
    gem 'listen'
  end
  puts 'installed.'
end

Daemons.run_proc('rename_proc.rb') do
  require 'listen'

  listen = Listen.to("#{ENV['HOME']}/Desktop") do |_modified, added, _removed|
    added.each do |file|
      path = file.split('/')
      filename = path.pop
      new_filename = case filename
                     when /Screen\ Shot/
                       "screen_shot_#{Time.now.to_i}.png"
                     when /Screen\ Recording/
                       "screen_recording_#{Time.now.to_i}.mov"
                     end

      next unless new_filename

      path.push new_filename
      puts "#{filename} -> #{new_filename}"
      File.rename(file, path.join('/'))
    end
  end

  listen.start
  sleep
end
