#!/usr/bin/env sh

phrases=("binding.pry" "console.log" "debugger" "<<<<<<< HEAD")
files=$(git diff --cached --name-only)
value=0

for file in $files; do
  if [[ ! $file =~ \.(md)$ ]]; then
    for i in ${!phrases[@]}; do
      phrase=${phrases[$i]}
      occurrences=$(grep -n "$phrase" $file)

      for o in ${!occurrences[@]}; do
        if [[ -n ${occurrences[o]} ]]; then
          value=1
          echo "$file \033[0;31m${occurrences[o]}\033[0m"
        fi
      done
    done
  fi
done

exit $value
