#!/usr/bin/env ruby

protected_branch = 'master'
current_branch = `git rev-parse --abbrev-ref HEAD`.chomp

if current_branch == protected_branch
  puts "You should not push directly to master. If you want to bypass this check, run `git push --no-verify`"
  exit(1)
end
