brew "ctags"
brew "ffmpeg"
brew "flow"
brew "fzf"
brew "grip"
brew "lua"
brew "neovim"
brew "ripgrep"
brew "tmux"
brew "zsh"
brew "glow"

cask "rectangle"
cask "ngrok"

# cask fonts
tap "homebrew/cask-fonts"
cask "font-meslo-lg-nerd-font"
