brew "ffmpeg"
brew "fzf"
brew "gh"
brew "neovim"
brew "ripgrep"
brew "tmux"
brew "zsh"

cask "rectangle"
cask "dbeaver-community"

# cask fonts
tap "homebrew/cask-fonts"
cask "font-meslo-lg-nerd-font"
